# Generated by Django 4.1 on 2023-08-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETP',
            fields=[
                ('etp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etp', models.CharField(max_length=10)),
                ('tipo_entrega', models.CharField(max_length=15)),
                ('tipo_etp', models.CharField(max_length=30)),
                ('elaborador', models.CharField(max_length=100)),
                ('demanda', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=30)),
                ('motivador', models.CharField(max_length=50)),
                ('des_macro_project', models.CharField(max_length=200)),
                ('obj_project', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=150)),
                ('info_complementar_atributos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OE',
            fields=[
                ('oe_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('TipoElemento', models.CharField(max_length=20)),
                ('numOE', models.CharField(max_length=15)),
                ('TipoOE', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('etp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dci_app.etp')),
            ],
        ),
    ]
